.TH "include/Zeta/Core/ResourceClasses/AnimationClass.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/ResourceClasses/AnimationClass.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <Zeta/Core/UtilityClasses/Ellipsis\&.hpp>\fP
.br
\fC#include <Zeta/Core/ResourceClasses/Resource\&.hpp>\fP
.br
\fC#include <Zeta/Core/UtilityClasses/Rectangle\&.hpp>\fP
.br
\fC#include <Zeta/Core/RPGClasses/LifeformState\&.hpp>\fP
.br
\fC#include <Zeta/Core/UtilityClasses/Vector2D\&.hpp>\fP
.br
\fC#include <Zeta/Core/ZSmallMap\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZeta::AnimationClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
