.TH "include/Zeta/Core/UtilityClasses/base64.h" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/UtilityClasses/base64.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBbase64_encode\fP (unsigned char const *, unsigned int len)"
.br
.ti -1c
.RI "std::string \fBbase64_decode\fP (std::string const &s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string base64_decode (std::string const &s)"

.SS "std::string base64_encode (unsigned char const *, unsigned intlen)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
