.TH "include/Zeta/Core/toLua_Binders/Binder.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/toLua_Binders/Binder.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtolua_Zeta_open\fP (lua_State *tolua_S)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int tolua_Zeta_open (lua_State *tolua_S)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
