.TH "include/Zeta/Core/UtilityClasses/Exception.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/UtilityClasses/Exception.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZeta::Exception\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
