.TH "include/Zeta/Core/MapClasses/Layer.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/MapClasses/Layer.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Zeta/Core/MapClasses/Map\&.hpp>\fP
.br
\fC#include <Zeta/Core/UtilityClasses/Vector2D\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZeta::Layer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBxmlpp\fP"
.br
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
