.TH "include/Zeta/Core/RPGClasses/LifeformClass.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/RPGClasses/LifeformClass.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Zeta/Core/ResourceClasses/Resource\&.hpp>\fP
.br
\fC#include <Zeta/Core/RPGClasses/Ability\&.hpp>\fP
.br
\fC#include <Zeta/Core/RPGClasses/Attribute\&.hpp>\fP
.br
\fC#include <Zeta/Core/ZetaConfig\&.hpp>\fP
.br
\fC#include <Zeta/Core/LuaTable\&.hpp>\fP
.br
\fC#include <Zeta/Core/LuaFunctor\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <random>\fP
.br
\fC#include <Zeta/Core/ZMap\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBZeta::Stats\fP"
.br
.ti -1c
.RI "class \fBZeta::LifeformClass\fP"
.br
.ti -1c
.RI "struct \fBZeta::LifeformClass::LifeformAbility\fP"
.br
.ti -1c
.RI "struct \fBZeta::LifeformClass::LuaAbility\fP"
.br
.ti -1c
.RI "class \fBZeta::LifeformClass::ChildParams\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
