.TH "include/Zeta/Core/RPGClasses/WorldEvent.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/RPGClasses/WorldEvent.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Zeta/Core/LuaPushable\&.hpp>\fP
.br
\fC#include <Zeta/Core/LuaTable\&.hpp>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZeta::WorldEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::DamageEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::DeathEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::InteractEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::AbilityUseEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::WorldExitEvent\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::CollisionEvent\fP"
.br
.ti -1c
.RI "union \fBZeta::WorldEvent::Event\fP"
.br
.ti -1c
.RI "struct \fBZeta::WorldEvent::CustomEvent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
