.TH "Zeta::ExternalObjectRequest::ObjectSource" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::ExternalObjectRequest::ObjectSource \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalObjectRequest\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBObjectType\fP { \fBObjectType::Field\fP, \fBObjectType::Enemy\fP, \fBObjectType::Npc\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmodule\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBspawnX\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBspawnY\fP"
.br
.ti -1c
.RI "enum 
.br
\fBZeta::ExternalObjectRequest::ObjectSource::ObjectType\fP \fBtype\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBZeta::ExternalObjectRequest::ObjectSource::ObjectType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIField \fP\fP
.TP
\fB\fIEnemy \fP\fP
.TP
\fB\fINpc \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::ExternalObjectRequest::ObjectSource::module"

.SS "\fBFloat\fP Zeta::ExternalObjectRequest::ObjectSource::spawnX"

.SS "\fBFloat\fP Zeta::ExternalObjectRequest::ObjectSource::spawnY"

.SS "enum \fBZeta::ExternalObjectRequest::ObjectSource::ObjectType\fP  Zeta::ExternalObjectRequest::ObjectSource::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
