.TH "Zeta::LifeformClassContainer" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::LifeformClassContainer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LifeformClassContainer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLifeformClass\fP & \fBget\fP ()"
.br
.ti -1c
.RI "\fBLifeformClassContainer\fP (const std::string &path)"
.br
.ti -1c
.RI "\fB~LifeformClassContainer\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBLifeformClass\fP * \fBlfClass\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::LifeformClassContainer::LifeformClassContainer (const std::string &path)"

.SS "Zeta::LifeformClassContainer::~LifeformClassContainer ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBLifeformClass\fP& Zeta::LifeformClassContainer::get ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLifeformClass\fP* Zeta::LifeformClassContainer::lfClass\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
