.TH "Zeta::StringOperations" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::StringOperations \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StringOperations\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBgetTokens\fP (const std::string &value, char delimiter, std::list< std::string > &tokenList, char stopOn=0, bool ignoreSpace=true)"
.br
.ti -1c
.RI "static std::string \fBtranslateUnixPath\fP (const std::string &thisPath, const std::string &relativePath)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void Zeta::StringOperations::getTokens (const std::string &value, chardelimiter, std::list< std::string > &tokenList, charstopOn = \fC0\fP, boolignoreSpace = \fCtrue\fP)\fC [static]\fP"

.SS "static std::string Zeta::StringOperations::translateUnixPath (const std::string &thisPath, const std::string &relativePath)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
