.TH "Zeta::LifeformClass::LifeformAbility" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::LifeformClass::LifeformAbility \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBabClass\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::LifeformClass::LifeformAbility::abClass"

.SS "int Zeta::LifeformClass::LifeformAbility::level"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
