.TH "Zeta::Event::KeyboardEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Event::KeyboardEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKeyboardKey\fP \fBkey\fP"
.br
.ti -1c
.RI "int \fBunichar\fP"
.br
.ti -1c
.RI "unsigned int \fBmodifiers\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBKeyboardKey\fP Zeta::Event::KeyboardEvent::key"

.SS "unsigned int Zeta::Event::KeyboardEvent::modifiers"

.SS "int Zeta::Event::KeyboardEvent::unichar"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
