.TH "Zeta::MulModifier" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::MulModifier \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MulModifier\&.hpp>\fP
.PP
Inherits \fBZeta::Modifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcalculate\fP (\fBAttributeValue\fP &value) const "
.br
.ti -1c
.RI "\fBMulModifier\fP (\fBAttributeValue\fP \fBmodValue\fP)"
.br
.ti -1c
.RI "\fB~MulModifier\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::MulModifier::MulModifier (\fBAttributeValue\fPmodValue)\fC [inline]\fP"

.SS "Zeta::MulModifier::~MulModifier ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::MulModifier::calculate (\fBAttributeValue\fP &value) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBZeta::Modifier\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
