.TH "Zeta::NonCopyable" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::NonCopyable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NonCopyable\&.hpp>\fP
.PP
Inherited by \fBZeta::SingleInstanced< AnimationEffectsManager >\fP, \fBZeta::SingleInstanced< ConsoleFunctions >\fP, \fBZeta::SingleInstanced< ConsoleManager >\fP, \fBZeta::SingleInstanced< FactionManager >\fP, \fBZeta::SingleInstanced< GUIManager >\fP, \fBZeta::SingleInstanced< Logger >\fP, \fBZeta::SingleInstanced< LuaEngine >\fP, \fBZeta::SingleInstanced< MainLoop >\fP, \fBZeta::SingleInstanced< MusicManager >\fP, \fBZeta::SingleInstanced< ResourceCache >\fP, \fBZeta::SingleInstanced< SaveManager >\fP, \fBZeta::SingleInstanced< Settings >\fP, \fBZeta::SingleInstanced< WorldManager >\fP, \fBZeta::SingleInstanced< XMLSchemaValidator >\fP, \fBZeta::SharedResource< RType >\fP, \fBZeta::SingleInstanced< type >\fP, and \fBZeta::SoundInstance\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonCopyable\fP ()=default"
.br
.ti -1c
.RI "\fBNonCopyable\fP (const \fBNonCopyable\fP &)=delete"
.br
.ti -1c
.RI "\fBNonCopyable\fP & \fBoperator=\fP (const \fBNonCopyable\fP &)=delete"
.br
.ti -1c
.RI "\fBNonCopyable\fP (\fBNonCopyable\fP &&)=default"
.br
.ti -1c
.RI "\fBNonCopyable\fP & \fBoperator=\fP (\fBNonCopyable\fP &&)=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::NonCopyable::NonCopyable ()\fC [default]\fP"

.SS "Zeta::NonCopyable::NonCopyable (const \fBNonCopyable\fP &)\fC [delete]\fP"

.SS "Zeta::NonCopyable::NonCopyable (\fBNonCopyable\fP &&)\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBNonCopyable\fP& Zeta::NonCopyable::operator= (const \fBNonCopyable\fP &)\fC [delete]\fP"

.SS "\fBNonCopyable\fP& Zeta::NonCopyable::operator= (\fBNonCopyable\fP &&)\fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
