.TH "Zeta::AggressiveBehaviourClass" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::AggressiveBehaviourClass \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AggressiveBehaviourClass\&.hpp>\fP
.PP
Inherits \fBZeta::BehaviourClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBehaviour\fP * \fBgetNewBehaviour\fP (\fBLifeform\fP &owner) const "
.br
.ti -1c
.RI "\fBAggressiveBehaviourClass\fP (\fBFloat\fP \fBaggroRange\fP, \fBFloat\fP \fBdriftRange\fP)"
.br
.ti -1c
.RI "\fB~AggressiveBehaviourClass\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFloat\fP \fBaggroRange\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBdriftRange\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::AggressiveBehaviourClass::AggressiveBehaviourClass (\fBFloat\fPaggroRange, \fBFloat\fPdriftRange)\fC [inline]\fP"

.SS "Zeta::AggressiveBehaviourClass::~AggressiveBehaviourClass ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBBehaviour\fP* Zeta::AggressiveBehaviourClass::getNewBehaviour (\fBLifeform\fP &owner) const\fC [virtual]\fP"

.PP
Implements \fBZeta::BehaviourClass\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFloat\fP Zeta::AggressiveBehaviourClass::aggroRange\fC [private]\fP"

.SS "\fBFloat\fP Zeta::AggressiveBehaviourClass::driftRange\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
