.TH "Zeta::BehaviourClass" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::BehaviourClass \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BehaviourClass\&.hpp>\fP
.PP
Inherited by \fBZeta::AggressiveBehaviourClass\fP, \fBZeta::IdleMovementClass\fP, \fBZeta::PassiveBehaviourClass\fP, and \fBZeta::WanderingMovementClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBBehaviour\fP * \fBgetNewBehaviour\fP (\fBLifeform\fP &owner) const =0"
.br
.ti -1c
.RI "\fBBehaviourClass\fP ()"
.br
.ti -1c
.RI "virtual \fB~BehaviourClass\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::BehaviourClass::BehaviourClass ()\fC [inline]\fP"

.SS "virtual Zeta::BehaviourClass::~BehaviourClass ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBBehaviour\fP* Zeta::BehaviourClass::getNewBehaviour (\fBLifeform\fP &owner) const\fC [pure virtual]\fP"

.PP
Implemented in \fBZeta::AggressiveBehaviourClass\fP, \fBZeta::WanderingMovementClass\fP, \fBZeta::IdleMovementClass\fP, and \fBZeta::PassiveBehaviourClass\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
