.TH "Zeta::ExternalObjectRequest" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::ExternalObjectRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalObjectRequest\&.hpp>\fP
.PP
Inherits \fBZeta::ContextOperation< RenderingContext >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBObjectSource\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBObject\fP * > & \fBgetObjects\fP ()"
.br
.ti -1c
.RI "void \fBhandle\fP (\fBRenderingContext\fP &context)"
.br
.ti -1c
.RI "\fBExternalObjectRequest\fP (const std::vector< \fBObjectSource\fP > &\fBobjectClasses\fP)"
.br
.ti -1c
.RI "\fB~ExternalObjectRequest\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetEnemy\fP (lua_State *lstate, \fBFloat\fP x, \fBFloat\fP y)"
.br
.ti -1c
.RI "void \fBgetNpc\fP (lua_State *lstate, \fBFloat\fP x, \fBFloat\fP y)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const std::vector< \fBObjectSource\fP > * \fBobjectClasses\fP"
.br
.ti -1c
.RI "std::vector< \fBObject\fP * > \fBobjects\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::ExternalObjectRequest::ExternalObjectRequest (const std::vector< \fBObjectSource\fP > &objectClasses)"

.SS "Zeta::ExternalObjectRequest::~ExternalObjectRequest ()"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::ExternalObjectRequest::getEnemy (lua_State *lstate, \fBFloat\fPx, \fBFloat\fPy)\fC [private]\fP"

.SS "void Zeta::ExternalObjectRequest::getNpc (lua_State *lstate, \fBFloat\fPx, \fBFloat\fPy)\fC [private]\fP"

.SS "std::vector<\fBObject\fP*>& Zeta::ExternalObjectRequest::getObjects ()\fC [inline]\fP"

.SS "void Zeta::ExternalObjectRequest::handle (\fBRenderingContext\fP &context)\fC [virtual]\fP"
Pure virtual member Function to be called by the ContextType 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP the \fBContext\fP that called it 
.RE
.PP

.PP
Implements \fBZeta::ContextOperation< RenderingContext >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::vector<\fBObjectSource\fP>* Zeta::ExternalObjectRequest::objectClasses\fC [private]\fP"

.SS "std::vector<\fBObject\fP*> Zeta::ExternalObjectRequest::objects\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
