.TH "Zeta::LuaString" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::LuaString \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LuaString\&.hpp>\fP
.PP
Inherits \fBZeta::LuaPushable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpushToLua\fP (lua_State *lstate)"
.br
.ti -1c
.RI "\fBLuaString\fP ()"
.br
.ti -1c
.RI "\fBLuaString\fP (const std::string &\fBstr\fP)"
.br
.ti -1c
.RI "\fB~LuaString\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLuaString\fP Wrapper class to be used as \fBLuaPushable\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::LuaString::LuaString ()\fC [inline]\fP"

.SS "Zeta::LuaString::LuaString (const std::string &str)\fC [inline]\fP"

.SS "Zeta::LuaString::~LuaString ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::LuaString::pushToLua (lua_State *lstate)\fC [virtual]\fP"

.PP
Implements \fBZeta::LuaPushable\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::LuaString::str\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
