.TH "Zeta::WorldEvent::AbilityUseEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldEvent::AbilityUseEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorldEvent\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLifeform\fP * \fBuser\fP"
.br
.ti -1c
.RI "\fBAbility\fP * \fBability\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBAbility\fP* Zeta::WorldEvent::AbilityUseEvent::ability"

.SS "\fBLifeform\fP* Zeta::WorldEvent::AbilityUseEvent::user"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
