.TH "Zeta::InteractField::OnCollisionHandler" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::InteractField::OnCollisionHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBZeta::Visitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBLifeform\fP &\fBobj\fP)"
.br
.ti -1c
.RI "void \fBhandle\fP (\fBPlayer\fP &\fBobj\fP)"
.br
.ti -1c
.RI "\fBOnCollisionHandler\fP (\fBInteractField\fP *\fBobj\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBInteractField\fP * \fBobj\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::InteractField::OnCollisionHandler::OnCollisionHandler (\fBInteractField\fP *obj)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::InteractField::OnCollisionHandler::handle (\fBLifeform\fP &obj)\fC [virtual]\fP"

.PP
Reimplemented from \fBZeta::Visitor\fP\&.
.SS "void Zeta::InteractField::OnCollisionHandler::handle (\fBPlayer\fP &obj)\fC [virtual]\fP"

.PP
Reimplemented from \fBZeta::Visitor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInteractField\fP* Zeta::InteractField::OnCollisionHandler::obj\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
