.TH "Zeta::ClassifiedAbility< AbClass >" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::ClassifiedAbility< AbClass > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassifiedAbility\&.hpp>\fP
.PP
Inherits \fBZeta::Ability\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const AbClass & \fBgetClass\fP () const "
.br
.ti -1c
.RI "\fBClassifiedAbility\fP (const AbClass &\fBabilityClass\fP, \fBLifeform\fP *\fBowner\fP, int \fBlevel\fP)"
.br
.ti -1c
.RI "virtual \fB~ClassifiedAbility\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const AbClass & \fBabilityClass\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename AbClass> \fBZeta::ClassifiedAbility\fP< AbClass >::\fBClassifiedAbility\fP (const AbClass &abilityClass, \fBLifeform\fP *owner, intlevel)\fC [inline]\fP"

.SS "template<typename AbClass> virtual \fBZeta::ClassifiedAbility\fP< AbClass >::~\fBClassifiedAbility\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename AbClass> const AbClass& \fBZeta::ClassifiedAbility\fP< AbClass >::getClass () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename AbClass> const AbClass& \fBZeta::ClassifiedAbility\fP< AbClass >::abilityClass\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
