.TH "Zeta::WanderingMovementClass" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WanderingMovementClass \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WanderingMovementClass\&.hpp>\fP
.PP
Inherits \fBZeta::BehaviourClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBehaviour\fP * \fBgetNewBehaviour\fP (\fBLifeform\fP &owner) const "
.br
.ti -1c
.RI "\fBWanderingMovementClass\fP (\fBFloat\fP \fBminWaitTime\fP, \fBFloat\fP \fBmaxWaitTime\fP, \fBFloat\fP \fBmaxDistance\fP, const std::string &\fBidleAction\fP='')"
.br
.ti -1c
.RI "\fB~WanderingMovementClass\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBidleAction\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBminWaitTime\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBmaxWaitTime\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBmaxDistance\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::WanderingMovementClass::WanderingMovementClass (\fBFloat\fPminWaitTime, \fBFloat\fPmaxWaitTime, \fBFloat\fPmaxDistance, const std::string &idleAction = \fC''\fP)"

.SS "Zeta::WanderingMovementClass::~WanderingMovementClass ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBBehaviour\fP* Zeta::WanderingMovementClass::getNewBehaviour (\fBLifeform\fP &owner) const\fC [virtual]\fP"

.PP
Implements \fBZeta::BehaviourClass\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::WanderingMovementClass::idleAction\fC [private]\fP"

.SS "\fBFloat\fP Zeta::WanderingMovementClass::maxDistance\fC [private]\fP"

.SS "\fBFloat\fP Zeta::WanderingMovementClass::maxWaitTime\fC [private]\fP"

.SS "\fBFloat\fP Zeta::WanderingMovementClass::minWaitTime\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
