.TH "Zeta::PassiveBehaviour" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::PassiveBehaviour \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PassiveBehaviour\&.hpp>\fP
.PP
Inherits \fBZeta::Behaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP (\fBFloat\fP elapsedTime)"
.br
.ti -1c
.RI "void \fBonDeath\fP ()"
.br
.ti -1c
.RI "\fBPassiveBehaviour\fP (\fBLifeform\fP &\fBowner\fP)"
.br
.ti -1c
.RI "\fB~PassiveBehaviour\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::PassiveBehaviour::PassiveBehaviour (\fBLifeform\fP &owner)\fC [inline]\fP"

.SS "Zeta::PassiveBehaviour::~PassiveBehaviour ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::PassiveBehaviour::onDeath ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBZeta::Behaviour\fP\&.
.SS "void Zeta::PassiveBehaviour::update (\fBFloat\fPelapsedTime)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBZeta::Updateable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
