.TH "Zeta::WorldEvent::Event" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldEvent::Event \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorldEvent\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDamageEvent\fP \fBdamageEvent\fP"
.br
.ti -1c
.RI "\fBDeathEvent\fP \fBdeathEvent\fP"
.br
.ti -1c
.RI "\fBInteractEvent\fP \fBinteractEvent\fP"
.br
.ti -1c
.RI "\fBAbilityUseEvent\fP \fBabilityUseEvent\fP"
.br
.ti -1c
.RI "\fBWorldExitEvent\fP \fBworldExitEvent\fP"
.br
.ti -1c
.RI "\fBCollisionEvent\fP \fBcollisionEvent\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBAbilityUseEvent\fP Zeta::WorldEvent::Event::abilityUseEvent"

.SS "\fBCollisionEvent\fP Zeta::WorldEvent::Event::collisionEvent"

.SS "\fBDamageEvent\fP Zeta::WorldEvent::Event::damageEvent"

.SS "\fBDeathEvent\fP Zeta::WorldEvent::Event::deathEvent"

.SS "\fBInteractEvent\fP Zeta::WorldEvent::Event::interactEvent"

.SS "\fBWorldExitEvent\fP Zeta::WorldEvent::Event::worldExitEvent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
