.TH "Zeta::IdleMovementClass" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::IdleMovementClass \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IdleMovementClass\&.hpp>\fP
.PP
Inherits \fBZeta::BehaviourClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBehaviour\fP * \fBgetNewBehaviour\fP (\fBLifeform\fP &owner) const "
.br
.ti -1c
.RI "\fBIdleMovementClass\fP ()"
.br
.ti -1c
.RI "\fB~IdleMovementClass\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::IdleMovementClass::IdleMovementClass ()\fC [inline]\fP"

.SS "Zeta::IdleMovementClass::~IdleMovementClass ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBBehaviour\fP* Zeta::IdleMovementClass::getNewBehaviour (\fBLifeform\fP &owner) const\fC [virtual]\fP"

.PP
Implements \fBZeta::BehaviourClass\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
