.TH "Zeta::FileLoader::FileStat" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::FileLoader::FileStat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileLoader\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for returning the \fBFile\fP data and size 
.SH "Member Data Documentation"
.PP 
.SS "char* Zeta::FileLoader::FileStat::data"

.SS "size_t Zeta::FileLoader::FileStat::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
