.TH "Zeta::TeleportField::CollisionHandler" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::TeleportField::CollisionHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBZeta::Visitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBPlayer\fP &obj)"
.br
.ti -1c
.RI "\fBCollisionHandler\fP (\fBTeleportField\fP &\fBcaller\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBTeleportField\fP & \fBcaller\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::TeleportField::CollisionHandler::CollisionHandler (\fBTeleportField\fP &caller)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::TeleportField::CollisionHandler::handle (\fBPlayer\fP &obj)\fC [virtual]\fP"

.PP
Reimplemented from \fBZeta::Visitor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTeleportField\fP& Zeta::TeleportField::CollisionHandler::caller\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
