.TH "Zeta::Tile::TileFrame" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Tile::TileFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tile\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTile\fP * \fBtile\fP"
.br
.ti -1c
.RI "\fBFloat\fP \fBuptime\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBTile\fP* Zeta::Tile::TileFrame::tile"

.SS "\fBFloat\fP Zeta::Tile::TileFrame::uptime"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
