.TH "Zeta::StickyObject" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::StickyObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StickyObject\&.hpp>\fP
.PP
Inherits \fBZeta::ChildObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStickyObject\fP (\fBFloat\fP x, \fBFloat\fP y, \fBObject\fP *\fBparent\fP, const std::string &\fBname\fP, const std::string &animationClass, const std::string &animName)"
.br
.ti -1c
.RI "\fB~StickyObject\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::StickyObject::StickyObject (\fBFloat\fPx, \fBFloat\fPy, \fBObject\fP *parent, const std::string &name, const std::string &animationClass, const std::string &animName)"

.SS "Zeta::StickyObject::~StickyObject ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
