.TH "Zeta::SystemEventListener" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::SystemEventListener \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SystemEventListener\&.hpp>\fP
.PP
Inherited by \fBZeta::GUIManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhandleEvent\fP (\fBEvent\fP &event)=0"
.br
.ti -1c
.RI "\fBSystemEventListener\fP ()"
.br
.ti -1c
.RI "virtual \fB~SystemEventListener\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::SystemEventListener::SystemEventListener ()\fC [inline]\fP"

.SS "virtual Zeta::SystemEventListener::~SystemEventListener ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Zeta::SystemEventListener::handleEvent (\fBEvent\fP &event)\fC [pure virtual]\fP"

.PP
Implemented in \fBZeta::GUIManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
