.TH "Zeta::Event::DisplayEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Event::DisplayEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Zeta::Event::DisplayEvent::height"

.SS "int Zeta::Event::DisplayEvent::width"

.SS "int Zeta::Event::DisplayEvent::x"

.SS "int Zeta::Event::DisplayEvent::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
