.TH "Zeta::Chance" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Chance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Chance\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset\fP (\fBFloat\fP \fBpercent\fP)"
.br
.ti -1c
.RI "bool \fBget\fP () const "
.br
.ti -1c
.RI "\fBChance\fP ()"
.br
.ti -1c
.RI "\fBChance\fP (\fBFloat\fP \fBpercent\fP)"
.br
.ti -1c
.RI "\fB~Chance\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFloat\fP \fBpercent\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::Chance::Chance ()"

.SS "Zeta::Chance::Chance (\fBFloat\fPpercent)"

.SS "Zeta::Chance::~Chance ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Zeta::Chance::get () const"

.SS "void Zeta::Chance::set (\fBFloat\fPpercent)"

.SH "Member Data Documentation"
.PP 
.SS "\fBFloat\fP Zeta::Chance::percent\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
