.TH "Zeta::WorldListener" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldListener \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorldListener\&.hpp>\fP
.PP
Inherited by \fBZeta::LuaListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBacceptEvent\fP (const \fBWorldEvent\fP &event)=0"
.br
.ti -1c
.RI "\fBWorldListener\fP ()"
.br
.ti -1c
.RI "virtual \fB~WorldListener\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::WorldListener::WorldListener ()\fC [inline]\fP"

.SS "virtual Zeta::WorldListener::~WorldListener ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Zeta::WorldListener::acceptEvent (const \fBWorldEvent\fP &event)\fC [pure virtual]\fP"

.PP
Implemented in \fBZeta::LuaListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
