.TH "Zeta::IdleMovement" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::IdleMovement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IdleMovement\&.hpp>\fP
.PP
Inherits \fBZeta::Behaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP (\fBFloat\fP elapsedTime)"
.br
.ti -1c
.RI "void \fBonDeath\fP ()"
.br
.ti -1c
.RI "\fBIdleMovement\fP (\fBLifeform\fP &\fBowner\fP)"
.br
.ti -1c
.RI "\fB~IdleMovement\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::IdleMovement::IdleMovement (\fBLifeform\fP &owner)\fC [inline]\fP"

.SS "Zeta::IdleMovement::~IdleMovement ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::IdleMovement::onDeath ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBZeta::Behaviour\fP\&.
.SS "void Zeta::IdleMovement::update (\fBFloat\fPelapsedTime)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBZeta::Updateable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
