.TH "Zeta::Map::MapTileset" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Map::MapTileset \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTileset\fP * \fBtileset\fP"
.br
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int Zeta::Map::MapTileset::id"

.SS "\fBTileset\fP* Zeta::Map::MapTileset::tileset"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
