.TH "Zeta::WorldEvent::InteractEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldEvent::InteractEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorldEvent\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLifeform\fP * \fBuser1\fP"
.br
.ti -1c
.RI "\fBLifeform\fP * \fBuser2\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBLifeform\fP* Zeta::WorldEvent::InteractEvent::user1"

.SS "\fBLifeform\fP* Zeta::WorldEvent::InteractEvent::user2"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
