.TH "Zeta::Event::MouseEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Event::MouseEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwheel\fP"
.br
.ti -1c
.RI "\fBMouseButton\fP \fBbutton\fP"
.br
.ti -1c
.RI "float \fBpressure\fP"
.br
.ti -1c
.RI "int \fBdx\fP"
.br
.ti -1c
.RI "int \fBdy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBMouseButton\fP Zeta::Event::MouseEvent::button"

.SS "int Zeta::Event::MouseEvent::dx"

.SS "int Zeta::Event::MouseEvent::dy"

.SS "float Zeta::Event::MouseEvent::pressure"

.SS "int Zeta::Event::MouseEvent::wheel"

.SS "int Zeta::Event::MouseEvent::x"

.SS "int Zeta::Event::MouseEvent::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
