.TH "Zeta::ConsoleFunctions" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::ConsoleFunctions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConsoleFunctions\&.hpp>\fP
.PP
Inherits \fBZeta::SingleInstanced< ConsoleFunctions >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisBoundsShown\fP () const "
.br
.ti -1c
.RI "void \fBsetBoundsShown\fP (bool \fBboundsShown\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBexit\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBecho\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBteleport\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBuseAbility\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBtoggleBoundBoxes\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBsetBoundPosition\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBsetBoundSize\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBoffsetBound\fP (const std::string &args)"
.br
.ti -1c
.RI "static std::string \fBreloadScript\fP (const std::string &args)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleFunctions\fP ()"
.br
.ti -1c
.RI "\fB~ConsoleFunctions\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBboundsShown\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSingleInstanced\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::ConsoleFunctions::ConsoleFunctions ()\fC [inline]\fP, \fC [private]\fP"

.SS "Zeta::ConsoleFunctions::~ConsoleFunctions ()\fC [inline]\fP, \fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static std::string Zeta::ConsoleFunctions::echo (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::exit (const std::string &args)\fC [static]\fP"

.SS "bool Zeta::ConsoleFunctions::isBoundsShown () const\fC [inline]\fP"

.SS "static std::string Zeta::ConsoleFunctions::offsetBound (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::reloadScript (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::setBoundPosition (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::setBoundSize (const std::string &args)\fC [static]\fP"

.SS "void Zeta::ConsoleFunctions::setBoundsShown (boolboundsShown)\fC [inline]\fP"

.SS "static std::string Zeta::ConsoleFunctions::teleport (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::toggleBoundBoxes (const std::string &args)\fC [static]\fP"

.SS "static std::string Zeta::ConsoleFunctions::useAbility (const std::string &args)\fC [static]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSingleInstanced\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Zeta::ConsoleFunctions::boundsShown\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
