.TH "Zeta::Stats" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LifeformClass\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBHP\fP"
.br
.ti -1c
.RI "static const std::string \fBMaxHP\fP"
.br
.ti -1c
.RI "static const std::string \fBMana\fP"
.br
.ti -1c
.RI "static const std::string \fBMaxMana\fP"
.br
.ti -1c
.RI "static const std::string \fBSpeed\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const std::string Zeta::Stats::HP\fC [static]\fP"

.SS "const std::string Zeta::Stats::Mana\fC [static]\fP"

.SS "const std::string Zeta::Stats::MaxHP\fC [static]\fP"

.SS "const std::string Zeta::Stats::MaxMana\fC [static]\fP"

.SS "const std::string Zeta::Stats::Speed\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
