.TH "Zeta::SingleInstanced< type >" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::SingleInstanced< type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SingleInstanced\&.hpp>\fP
.PP
Inherits \fBZeta::NonCopyable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleInstanced\fP ()"
.br
.ti -1c
.RI "\fB~SingleInstanced\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static type & \fBgetInstance\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename type> \fBZeta::SingleInstanced\fP< type >::\fBSingleInstanced\fP ()\fC [inline]\fP"

.SS "template<typename type> \fBZeta::SingleInstanced\fP< type >::~\fBSingleInstanced\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename type> static type& \fBZeta::SingleInstanced\fP< type >::getInstance ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
