.TH "Zeta::WorldManager::WorldListenerPair" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldManager::WorldListenerPair \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWorldListener\fP * \fBlistener\fP"
.br
.ti -1c
.RI "\fBWorldEvent::Type\fP \fBtype\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBWorldListener\fP* Zeta::WorldManager::WorldListenerPair::listener"

.SS "\fBWorldEvent::Type\fP Zeta::WorldManager::WorldListenerPair::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
