.TH "Zeta::WorldEvent::CustomEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldEvent::CustomEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorldEvent\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel\fP"
.br
.ti -1c
.RI "\fBLuaTable\fP \fBtable\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::WorldEvent::CustomEvent::channel"

.SS "\fBLuaTable\fP Zeta::WorldEvent::CustomEvent::table\fC [mutable]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
