.TH "Zeta::DirectionalProjectile" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::DirectionalProjectile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DirectionalProjectile\&.hpp>\fP
.PP
Inherits \fBZeta::Projectile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectionalProjectile\fP (const \fBProjectileClass\fP *cls, \fBActiveAbility\fP *parent, \fBFloat\fP x, \fBFloat\fP y)"
.br
.ti -1c
.RI "\fB~DirectionalProjectile\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBmove\fP ()"
.br
.ti -1c
.RI "void \fBcalculateTargetPosition\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::DirectionalProjectile::DirectionalProjectile (const \fBProjectileClass\fP *cls, \fBActiveAbility\fP *parent, \fBFloat\fPx, \fBFloat\fPy)"

.SS "Zeta::DirectionalProjectile::~DirectionalProjectile ()"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::DirectionalProjectile::calculateTargetPosition ()\fC [private]\fP"

.SS "void Zeta::DirectionalProjectile::move ()\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
