.TH "Zeta::Map::ObjectPair" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Map::ObjectPair \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP * \fBgetObject\fP ()"
.br
.ti -1c
.RI "bool \fBisToBeDeleted\fP ()"
.br
.ti -1c
.RI "\fBObjectPair\fP (\fBObject\fP *\fBobj\fP, bool \fBtoBeDeleted\fP)"
.br
.ti -1c
.RI "\fB~ObjectPair\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBObject\fP * \fBobj\fP"
.br
.ti -1c
.RI "bool \fBtoBeDeleted\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::Map::ObjectPair::ObjectPair (\fBObject\fP *obj, booltoBeDeleted)\fC [inline]\fP"

.SS "Zeta::Map::ObjectPair::~ObjectPair ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBObject\fP* Zeta::Map::ObjectPair::getObject ()\fC [inline]\fP"

.SS "bool Zeta::Map::ObjectPair::isToBeDeleted ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBObject\fP* Zeta::Map::ObjectPair::obj\fC [private]\fP"

.SS "bool Zeta::Map::ObjectPair::toBeDeleted\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
