.TH "Zeta::Updateable" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::Updateable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Updateable\&.hpp>\fP
.PP
Inherited by \fBZeta::ActiveAbility\fP, \fBZeta::AnimationHandler\fP, \fBZeta::AnimationPlayer\fP, \fBZeta::Behaviour\fP, \fBZeta::Effect\fP, \fBZeta::GUIManager\fP, \fBZeta::Map\fP, \fBZeta::Object\fP, \fBZeta::Regeneration\fP, \fBZeta::Tile\fP, \fBZeta::Timer\fP, and \fBZeta::WorldManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdate\fP (\fBFloat\fP elapsedTime)=0"
.br
.ti -1c
.RI "\fBUpdateable\fP ()"
.br
.ti -1c
.RI "virtual \fB~Updateable\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::Updateable::Updateable ()\fC [inline]\fP"

.SS "virtual Zeta::Updateable::~Updateable ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Zeta::Updateable::update (\fBFloat\fPelapsedTime)\fC [pure virtual]\fP"

.PP
Implemented in \fBZeta::Map\fP, \fBZeta::WorldManager\fP, \fBZeta::Tile\fP, \fBZeta::CEGUIObject\fP, \fBZeta::Timer\fP, \fBZeta::ChildObject\fP, \fBZeta::AnimationPlayer\fP, \fBZeta::Lifeform\fP, \fBZeta::AnimationHandler\fP, \fBZeta::GUIManager\fP, \fBZeta::Effect\fP, \fBZeta::ActiveAbility\fP, \fBZeta::DurableEffect\fP, \fBZeta::Player\fP, \fBZeta::Projectile\fP, \fBZeta::WanderingMovement\fP, \fBZeta::OverTimeEffect\fP, \fBZeta::Regeneration\fP, \fBZeta::StaticObject\fP, \fBZeta::InteractObject\fP, \fBZeta::InteractField\fP, \fBZeta::Enemy\fP, \fBZeta::TeleportField\fP, \fBZeta::IdleMovement\fP, \fBZeta::PassiveBehaviour\fP, and \fBZeta::AggressiveBehaviour\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
