.TH "Zeta::AllegroEvent" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::AllegroEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AllegroEvent\&.hpp>\fP
.PP
Inherits \fBZeta::Event\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAllegroEvent\fP (ALLEGRO_EVENT &event)"
.br
.ti -1c
.RI "\fB~AllegroEvent\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::AllegroEvent::AllegroEvent (ALLEGRO_EVENT &event)"

.SS "Zeta::AllegroEvent::~AllegroEvent ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
