.TH "Zeta::WorldManager::CustomListenerPair" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::WorldManager::CustomListenerPair \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel\fP"
.br
.ti -1c
.RI "\fBWorldListener\fP * \fBlistener\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Zeta::WorldManager::CustomListenerPair::channel"

.SS "\fBWorldListener\fP* Zeta::WorldManager::CustomListenerPair::listener"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
