.TH "Zeta::ResourceReleaseRequest" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zeta::ResourceReleaseRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ResourceReleaseRequest\&.hpp>\fP
.PP
Inherits \fBZeta::ContextOperation< ResourceContext >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (\fBContext\fP< \fBResourceContext\fP > &context)"
.br
.ti -1c
.RI "\fBResourceReleaseRequest\fP ()"
.br
.ti -1c
.RI "\fB~ResourceReleaseRequest\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zeta::ResourceReleaseRequest::ResourceReleaseRequest ()"

.SS "Zeta::ResourceReleaseRequest::~ResourceReleaseRequest ()"

.SH "Member Function Documentation"
.PP 
.SS "void Zeta::ResourceReleaseRequest::handle (\fBContext\fP< \fBResourceContext\fP > &context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
