.TH "include/Zeta/Core/ZSet.hpp" 3 "Wed Feb 10 2016" "Zeta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Zeta/Core/ZSet.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_set>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZeta\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename Key > using \fBZeta::ZSet\fP = std::unordered_set< Key >"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zeta from the source code\&.
